// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdFlAqWuj1HdIYPyliMovXWRSxZmJ19nM',
    appId: '1:256662023792:android:5192080ac6731bd065ceb5',
    messagingSenderId: '256662023792',
    projectId: 'eko-sortify-a3356',
    storageBucket: 'eko-sortify-a3356.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZT3R5Z8NypblGh4iCfykItFkOYHfZgQ4',
    appId: '1:256662023792:ios:1fe72466313ee2a765ceb5',
    messagingSenderId: '256662023792',
    projectId: 'eko-sortify-a3356',
    storageBucket: 'eko-sortify-a3356.appspot.com',
    androidClientId: '256662023792-6s9v0grja56ds52hevgma5tggo2uqpku.apps.googleusercontent.com',
    iosClientId: '256662023792-4g3qq4l8pe8rgna31gn83d2kdbt5l221.apps.googleusercontent.com',
    iosBundleId: 'com.example.aq',
  );

}